# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=4, max_digits=6)),
                ('laungagues', models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('FR', 'French')], max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
